---
- hosts: workstations
  become: true
  tasks:
    - name: Install packages
      package:
        name: "{{ item }}"
        state: "present"
      loop:
        - vim
        - terminator
        - git
        - python3-pip
        - tldr
        - htop
        - gnome-shell-extensions
        - zsh
        - curl
        - jq
        - python-pip
        - virtualenvwrapper
        - pwgen
        - net-tools
        - whois
        - vagrant
        - virtualbox
        - nmap
        - lolcat
    - name: Install pip dependecies
      pip:
        name: "{{ item }}"
      loop: 
        - pytest
        - thefuck
        - virtualenv 

